[project]
name = "ai-translator-agent"
version = "0.1.0"
description = "Jednoduchý AI agent s OpenAI API pro překlad EN <-> CZ"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.66.3",
    "python-dotenv>=1.0.1",
]
